name: handwritting_detection
channels:
  - defaults
  - conda-forge
dependencies:
  - aom=3.12.1
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cairo=1.18.4
  - dav1d=1.2.1
  - expat=2.7.3
  - fontconfig=2.15.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - gettext=0.21.0
  - giflib=5.2.2
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - jpeg=9f
  - lcms2=2.16
  - leptonica=1.82.0
  - lerc=4.0.0
  - libarchive=3.8.2
  - libavif=1.1.1
  - libcxx=20.1.8
  - libdeflate=1.22
  - libffi=3.4.4
  - libglib=2.84.4
  - libiconv=1.16
  - libopenjpeg=2.5.4
  - libpng=1.6.50
  - libtiff=4.7.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - lz4-c=1.9.4
  - ncurses=6.5
  - openjpeg=2.5.4
  - openssl=3.6.0
  - packaging=25.0
  - pcre2=10.46
  - pillow=12.0.0
  - pip=25.2
  - pixman=0.46.4
  - pytesseract=0.3.10
  - python=3.10.19
  - python-dotenv=1.2.1
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tesseract=5.2.0
  - tk=8.6.15
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - aistudio-sdk==0.3.8
      - annotated-types==0.7.0
      - anyio==4.11.0
      - bce-python-sdk==0.9.52
      - cachetools==6.2.2
      - certifi==2025.11.12
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorlog==6.10.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - easyocr==1.7.2
      - exceptiongroup==1.3.0
      - filelock==3.20.0
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - future==1.0.0
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.28.1
      - google-api-python-client==2.187.0
      - google-auth==2.43.0
      - google-auth-httplib2==0.2.1
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.72.0
      - grpcio==1.76.0
      - grpcio-status==1.71.2
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httplib2==0.31.0
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - imageio==2.37.2
      - imagesize==1.4.1
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - modelscope==1.31.0
      - mpmath==1.3.0
      - networkx==3.4.2
      - ninja==1.13.0
      - numpy==2.2.6
      - opencv-contrib-python==4.10.0.84
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.12.0.88
      - opt-einsum==3.3.0
      - paddleocr==3.3.2
      - paddlepaddle==3.2.2
      - paddlex==3.3.9
      - pandas==2.3.3
      - polars==1.35.2
      - polars-runtime-32==1.35.2
      - prettytable==3.17.0
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - psutil==7.1.3
      - py-cpuinfo==9.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyclipper==1.3.0.post6
      - pycryptodome==3.23.0
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pyparsing==3.2.5
      - pypdfium2==5.0.0
      - python-bidi==0.6.7
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2025.11.3
      - requests==2.32.5
      - rsa==4.9.1
      - ruamel-yaml==0.18.16
      - ruamel-yaml-clib==0.2.15
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scipy==1.15.3
      - shapely==2.1.2
      - six==1.17.0
      - sniffio==1.3.1
      - sympy==1.14.0
      - tifffile==2025.5.10
      - timm==1.0.22
      - tokenizers==0.22.1
      - torch==2.9.1
      - torchvision==0.24.1
      - tqdm==4.67.1
      - transformers==4.57.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - ujson==5.11.0
      - ultralytics==8.3.228
      - ultralytics-thop==2.0.18
      - uritemplate==4.2.0
      - urllib3==2.5.0
      - wcwidth==0.2.14
